# Generated by Django 2.0.1 on 2018-01-20 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalancingAuthority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('megawatts', models.DecimalField(decimal_places=1, max_digits=10)),
                ('market', models.CharField(max_length=200)),
                ('balancing_authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caiso.BalancingAuthority')),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caiso.Fuel')),
            ],
        ),
        migrations.CreateModel(
            name='GenerationMix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='generation',
            name='generation_mix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caiso.GenerationMix'),
        ),
    ]
