# Generated by Django 2.0.1 on 2018-01-25 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caiso', '0003_auto_20180123_0313'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationMix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('balancing_authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caiso.BalancingAuthority')),
            ],
        ),
        migrations.RemoveField(
            model_name='generation',
            name='balancing_authority',
        ),
        migrations.RemoveField(
            model_name='generation',
            name='timestamp',
        ),
    ]
